# These contexts will be applied to every buyable permission.
global-contexts:
  server: Survival

defaults:
  menu:
    title: "Upgrades"
    rows: 3
  menu-tem:
    material: BLACK_STAINED_GLASS_PANE
    display-name: ""
    lore: []
    amount: 1
  menu-element:
    type: normal
  sub-menu-element:
    price: 9999
    must-have-perms:
      "&cBuy": buy.upgrades.perm

enchant-on-have: true
color-on-have: true

have-color: "&2&l"
not-have-color: "&c&l"

main-menu:
  title: "Example title (main menu)"
  rows: 3
  items:
    1:
      material: CHEST
      display-name: "Example display name (main menu)"
      lore:
        - "Example lore 1 (main menu)"
        - "Example lore 2 (main menu)"
      amount: 1
      slot: 0
      sub-menu: ExampleMenu

Messages:
  plugin-prefix: "&b&l[&3&lUpgrades&b&l] &r"
  no-permission: "&cYou don't have permission to do that."
  successful-buy: "&2Successful buy."
  already-have: "&cYou already have this one."
  no-money: "&cYou don't have enough money to buy this."
  dont-have-must-have-perm: "&cYou dont have must have permission: &l"